### ISSUE TITLE
·

### ISSUE THREAD

**Issue by ghost** [oppo-us-research/USST#3]
·

**Comment by Cogito2012** [comment]
@kuri12342 [方差只是在训练过程中计算loss使用的，见代码：[uncts = self.predict_uncertainty(future_pred)](https://github.com/oppo-us-research/USST/blob/bc09a79db8bf947c700ac3edaa38928e1525fc27/src/models/TransformerSSM.py#L147) 以及 [def compute_loss](https://github.com/oppo-us-research/USST/blob/bc09a79db8bf947c700ac3edaa38928e1525fc27/src/Losses.py#L49)。

注意这里是假定每个坐标点服从一个由均值、方差定义的高斯分布，用网络学习方差的预测，类似于一种训练的正则方式。而在测试中，只需要均值即可，无需测试过程中的采样。

**Comment by ghost** [comment]
·

**Comment by Cogito2012** [comment]
@kuri12342 跟VAE这类隐变量模型不太一样，这个方法测试过程可以认为是确定性的。当然也可以测试过程多次采样平均，但我记得效果不那么好
