### ISSUE TITLE
Could you offer the H2O-DT dataset

### ISSUE THREAD

**Issue by Claymore715** [oppo-us-research/USST#5]
Hello, I am interested in your paper, but I find that the H2O-DT dataset and the visualization code is missing in this repository. It would be great if you could provide it.

**Comment by Cogito2012** [comment]
@Claymore715 
Sure, here is the [H2O-DT annotations](https://1drv.ms/u/s!Akf7nSDT8d4Kr1gdL2EOACQ182Ua). You can simply unzip this file, rename the folder as `traj`, and use it to replace the H2O-PT annotations `H2O/Ego3DTraj/traj`.

For the H2O dataset, we didn't implement the visualization of the model outputs, but you can do this by referring to the annotation visualization code: [USST/preprocess/H2O/visualize.py](https://github.com/oppo-us-research/USST/blob/master/preprocess/H2O/visualize.py).

**Comment by Claymore715** [comment]
Thanks.

**Comment by BIT-MJY** [comment]
Dear @Claymore715 ,

Many thanks for your great contributions to hand trajectory prediction! The link of H2O-DT annotations is broken again. Could you please update it?
