### ISSUE TITLE
About H2O test

### ISSUE THREAD

**Issue by XIAOLIANG64** [oppo-us-research/USST#8]
Thank you very much for your work！
I am currently facing some issues

I would like to know how to evaluate the model on the H2O dataset.

eg:For action prediction, you need to put action id number as the key and action label number as value of the json file. action_labels.json {"modality": "hand+obj", "1": 32, "2": 11, "3": 14, ... "241": 16, "242": 22 } Make answer.zip with this json file to submit your result to CodaLab.

**Comment by Cogito2012** [comment]
@XIAOLIANG64 Thanks for your interest!
The model trained in our project only targets 3D trajectory forecasting, so this repo does not support for action prediction.

If you would like to test the action prediction performance on the H2O leader board, you may need to modify the model architecture (e.g., input & output layers), and re-train the model with action labels from the original H2O dataset.

Hope this could be helpful:)
